version: '2.4'
services:
  db:
    container_name: database
    image: 'mysql:8'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: schedule
    volumes:
      - './src/main/resources/initDb.sql:/docker-entrypoint-initdb.d/initDb.sql'
    ports:
      - '127.0.0.1:3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: schedule
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy